# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    guzzle:
        class: GuzzleHttp\Client

    token_storage_session:
        class: OAuth\Common\Storage\Session

    api_adapter_factory:
        class: AppBundle\ApiAdapter\ProviderApiAdapterFactory
        arguments: ["@service_container"]

    user_data:
        class: AppBundle\UserData\UserData
        arguments: ["@database_connection", "@entity_measurement_type"]

    entity_provider:
        class: AppBundle\Entity\Provider
        arguments: ["@database_connection"]

    entity_measurement_type:
        class: AppBundle\Entity\MeasurementType
        arguments: ["@database_connection"]

    entity.measurement:
        class: AppBundle\Entity\Measurement
        arguments: ["@database_connection"]

    entity.measurement_event:
        class: AppBundle\Entity\MeasurementEvent
        arguments: ["@database_connection"]