<?php

namespace AppBundle\Entity;

/**
 * OAuthAccessTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OAuthAccessTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
